import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import SideBar from "@/components/SideBar";

const manrope = localFont({ src: "../public/fonts/SignikaNegative-Regular.ttf" })

export const metadata: Metadata = {
  title: "Nomeo Music 1.0",
  description: "A music app generated by create next app, it enables you to stream music online.",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <SideBar>
          {children}
        </SideBar>
      </body>
    </html>
  );
}
