import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import SideBar from "@/components/SideBar";
import SupabaseProvider from "@/providers/SupabaseProvider";
import UserProvider from "@/providers/UserProvider";
import ModalProvider from "@/providers/ModalProvider";
import ToasterProvider from "../providers/ToasterProvider";
import { fetchSongsByUserId } from "@/actions/fetchSongsByUserId";
import MediaPlayer from "@/components/MediaPlayer";
import { fetchActiveSubscription } from "@/actions/fetchActiveSubscription";

const customFont = localFont({ src: "../public/fonts/Barlow-Regular.ttf" })

export const metadata: Metadata = {
  title: "Nomeo Music 1.0",
  description: "A music app generated by create next app, it enables you to stream music online.",
};

export const revalidate = 0;

export default async function RootLayout({children}: Readonly<{children: React.ReactNode}>) {

  const userSongs = await fetchSongsByUserId();
  const activeSubscription = await fetchActiveSubscription();
  return (
    <html lang="en">
      <body className={customFont.className}>
        <ToasterProvider />
        <SupabaseProvider>
          <UserProvider>
            <ModalProvider subscriptions={activeSubscription}/>
            <SideBar userSongs={userSongs}>
              {children}
            </SideBar>
            <MediaPlayer/>
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
