import { fetchUserLikedSongs } from '@/actions/fetchUserLikedSongs'
import Header from '@/components/Header';
import Image from 'next/image';
import React from 'react'
import LikedContent from './components/LikedContent';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Nomeo Music 1.0 | Liked",
  description: "A music app generated by create next app, it enables you to stream music online.",
};


const LikedPage = async () => {
  const likedSongs = await fetchUserLikedSongs();

  return (
    <div className='bg-neutral-900 rounded-lg h-full w-full overflow-hidden overflow-y-auto'>
      <Header>
        <div className="mt-20">
          <div className="flex flex-col md:flex-row items-center gap-x-5">
            <div className="relative h-52 w-52 rounded-md md:w-48 md:h-48 overflow-hidden">
              <Image src='/images/playlist.png' alt='playlist_banner' className='object-cover rounded-md' fill />
            </div>
            <div className='flex flex-col gap-y-2 mt-4 md:mt-0 lg:text-lg'>
              <p className='font-semibold hidden md:block'>Playlist</p>
              <h1 className='text-white text-4xl sm:text-5xl lg:text-7xl font-bold'>Liked Songs</h1>
            </div>
          </div>
        </div>
      </Header>
      <LikedContent songs={likedSongs}/>
    </div>
  )
}

export default LikedPage